I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1994, in script call
    call mapcall([10,10],stagehome)
  File "game/Movement.rpy", line 120, in script call
    call Returns
  File "game/Movement.rpy", line 461, in script call
    call checkwalls
  File "game/Movement.rpy", line 62, in script
    python:
  File "game/Movement.rpy", line 64, in <module>
    objectbelow = boxsheet[playerypos+1][playerxpos]
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1994, in script call
    call mapcall([10,10],stagehome)
  File "game/Movement.rpy", line 120, in script call
    call Returns
  File "game/Movement.rpy", line 461, in script call
    call checkwalls
  File "game/Movement.rpy", line 62, in script
    python:
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Movement.rpy", line 64, in <module>
    objectbelow = boxsheet[playerypos+1][playerxpos]
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 847, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Darwin-19.3.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
SoftWar - DEMO 1.0
Mon Mar 23 01:34:39 2020
